### ISSUE TITLE
Error Launching bot at master branch

### ISSUE THREAD

**Issue by axisepm** [progapandist/coordinator-bot#4]
Hi there! 

It seems there is a bug with the current code at Master: whenever I try to launch the code I get the following error: 
~/coordinator-bot$ rackup -p 5000

/home/seba/coordinator-bot/persistent_menu.rb:4:in `enable': uninitialized constant Facebook::Messenger::Thread (NameError)
Did you mean?  Thread
        from /home/seba/coordinator-bot/bot.rb:12:in `<top (required)>'
        from /home/seba/coordinator-bot/config.ru:2:in `require_relative'
        from /home/seba/coordinator-bot/config.ru:2:in `block in <main>'
        from /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
        from /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
        from /home/seba/coordinator-bot/config.ru:in `new'
        from /home/seba/coordinator-bot/config.ru:in `<main>'
        from /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
        from /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
        from /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
        from /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        from /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
        from /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
        from /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:283:in `start'
        from /var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:148:in `start'
        from /var/lib/gems/2.3.0/gems/rack-2.0.3/bin/rackup:4:in `<top (required)>'
        from /usr/local/bin/rackup:23:in `load'
        from /usr/local/bin/rackup:23:in `<main>'

Regards, 
Sebastian

**Comment by progapandist** [comment]
Hi! This tutorial evolved into a project called [Rubotnik](https://github.com/progapandist/rubotnik/), so I advise you to refer to this repo from now on, the [README](https://github.com/progapandist/rubotnik/) contains all instructions.

**Comment by axisepm** [comment]
thank you so much!
